/*

 __EXPORT_HEADER_FILENAME__

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : __MAP_WIDTH__ x __MAP_HEIGHT__
   Tile set      : __IMPORT_TILED_FILENAME__
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by __PROGRAM_NAME__ __PROGRAM_VERSION__ on __CURRENT_DATE__

*/

#ifndef __INCLUDE_GUARD__
#define __INCLUDE_GUARD__

#define __DEFINE_MAP_WIDTH__  __MAP_WIDTH__
#define __DEFINE_MAP_HEIGHT__ __MAP_HEIGHT__

extern const unsigned char __VAR_MAP_NAME__[];

#endif /* __INCLUDE_GUARD__ */
